### ISSUE TITLE
README中のサンプルコードがリンクとして解釈されてしまっている

### ISSUE THREAD

**Issue by tomoasleep** [jpmobile/jpmobile#101]
https://github.com/tomoasleep/jpmobile#使用例 中にある`env['rack.jpmobile']` は恐らくソースコード中でのキャリアクラスへのアクセス方法を指していると思うのですが、rdocではこの記法だとリンクとして解釈されてしまいます。
(http://docs.seattlerb.org/rdoc/RDoc/Markup.html#class-RDoc::Markup-label-Links 中の`label[url]`のようにリンクとされて解釈されてしまっています。)

※ `<tt>`などのタグで囲うとエスケープされるようなのでこれをエスケープ出来ないか試みたのですが、GitHub上のバグ(?)もしくは仕様によって、現在はエスケープ出来ないようです。

以下の様にGitHubに報告はしてあります。
https://gist.github.com/tomoasleep/c468e518e4817f91eb02

**Comment by rust** [comment]
:+1: :bow:

**Comment by rust** [comment]
こちら 8214f139512b69d286f2bfa7791322dc3ad5d00c で Markdown に変更済み
