### ISSUE TITLE
raise error in `fetching from https://rubygems.org/` when bundle install

### ISSUE THREAD

**Issue by VoTaiTri** [jpmobile/jpmobile#115]
recently, i get error when i implement `bundle install` in fetching from `https://rubygems.org/` like below : 
```
Fetching gem metadata from https://rubygems.org/.Retrying dependency api due to error (2/4): Bundler::HTTPError Net::HTTPInternalServerError: <h1>Internal Server Error</h1>
Retrying dependency api due to error (3/4): Bundler::HTTPError Net::HTTPInternalServerError: <h1>Internal Server Error</h1>
Retrying dependency api due to error (4/4): Bundler::HTTPError Net::HTTPInternalServerError: <h1>Internal Server Error</h1>
```
i think this error was caused by `jpmobile`
so i comment out `gem 'jpmobile'` in `Gemfile`, it's ok
but i get error `undefined method 'smart_phone?'` when i run `rspec`

i'm so sorry because i can't speak Japanese 
i need your help
thanks

**Comment by rust** [comment]
I think the first error was caused by Gem server error. Please retry.

Second error is caused by the lack of `jpmobile`.

**Comment by VoTaiTri** [comment]
thanks @rust 
i've rechecked
but `bundle install` just run when i comment out gem `jpmobile`
when i implement `bundle` with `jpmobile`, it still raise error look like above

**Comment by rust** [comment]
Did `bundle install` command fail?

I know this situation, and `bundle install` command is very slow, but finally this command done successfully.

**Comment by igaiga** [comment]
I've got the error on `bundle install` process.
`bundle init` and add `gem 'jpmobile'` line into Gemfile, the error occurs.
On both Bundler 1.10.x and 1.11.x versions, Ruby2.2.3 and 2.3.0 occurs the error.

And sometimes bundle install success for a minute, but sometimes timed out. That's same as rust said.

**Comment by igaiga** [comment]
Using --verbose option for bundle, got following messages.
```
$ bundle install --verbose
...
Retrying dependency api due to error (4/4): Bundler::HTTPError Net::HTTPInternalServerError: <h1>Internal Server Error</h1>
Query Gemcutter Dependency Endpoint API: jpmobile
HTTP GET https://bundler.rubygems.org/api/v1/dependencies?gems=jpmobile
HTTP 500 Internal Server Error
```
`https://bundler.rubygems.org/api/v1/dependencies?gems=jpmobile` access occurs Internal Server Error.

**Comment by eagletmt** [comment]
Fixed in https://github.com/bundler/bundler-api/issues/118 .
It's obviously a server-side error.

**Comment by igaiga** [comment]
@eagletmt Thanks! I've confirmed fixing the problem.

**Comment by rust** [comment]
@eagletmt Thank you for your cooperation :bow:

**Comment by VoTaiTri** [comment]
@rust @igaiga @eagletmt  
thanks you very much
