### ISSUE TITLE
Source change broke Rails < 5.1 support

### ISSUE THREAD

**Issue by inket** [jpmobile/jpmobile#135]
The new version of jpmobile broke Rails < 5.1 support because of this change: https://github.com/jpmobile/jpmobile/commit/8d531418c4c6c135e116eec7c9bb35b338caf6f2

`extract_handler_and_format_and_variant` expects 2 arguments

**Comment by rust** [comment]
The `master` branch supports Rails > 5.1 only. Please read the following document.

https://github.com/jpmobile/jpmobile/wiki/Version-:-Jpmobile-vs-Rails

**Comment by inket** [comment]
You should use

```ruby
gem.add_runtime_dependency 'rails', '~> 5.1.0'
``` 

and not

```ruby
gem.add_development_dependency 'rails', '~> 5.1.0'
```

to correctly declare dependency so that Bundler doesn't install conflicting versions.

**Comment by rust** [comment]
Thank you for suggestion. I understand such problem in bundle install. But jpmobile is not only Rails plugin, but also supports Rack application (Sinatra, Padrino, etc.). So I don't use `add_runtime_dependency`.

Please specify jpmobile version corresponding to Rails version.
