### ISSUE TITLE
Ruby 2.7 support on jpmobile 7.0

### ISSUE THREAD

**Issue by r7kamura** [jpmobile/jpmobile#185]
## 概要

rails 7.0がruby 2.7で動くため、jpmobile 7.0もruby 2.7で動くと嬉しいと思うのですが、どうでしょうか。

### 背景

現在、次のような構成のRailsアプリの開発に何件か携わっています。

- rails 6.1
- jpmobile 6.1
- ruby 2.7

rails 7.0に移行したいのですが、現在はjpmobile 7.0がruby 3.0以降にしか対応しておらず、困っています。

### 今後どのRubyのバージョンをサポートすべきか

jpmobileとしては、「対応するRailsがサポートしているRubyのバージョンをサポートする」とするのが良いのではと考えていますが、どうでしょうか。

**Comment by rust** [comment]
これ意図通りではないので、修正しますね 🙏

**Comment by rust** [comment]
https://github.com/jpmobile/jpmobile/commit/9edba740b16b0f79ddb5f8b853c0f22cc1420b0f こちらで対応入れて、

https://github.com/jpmobile/jpmobile/commit/2e0eaabf547d9adb54a5c2bf7010852ade46f3d8 7.0.1 リリースしました

**Comment by r7kamura** [comment]
リリースありがとうございます、助かります！！ 🎉
