### ISSUE TITLE
非PC向けテンプレートだけが存在するエンドポイントで、コントローラでのアクション定義を省略できない

### ISSUE THREAD

**Issue by r7kamura** [jpmobile/jpmobile#197]
Railsでは、例えば app/views/home/index.html.erb が存在する場合、次のように `#index` を定義しなくても問題ありません。

```ruby
class HomeController < ApplicationController
end
```

しかし app/views/home/index_smart_phone.html.erb  だけが存在する場合、次のように空の `#index` を定義してあげる必要があります。

```ruby
class HomeController < ApplicationController
  def index
  end
end
```

jpmobile側の措置により、この空のメソッド定義を不要にすることはできないものでしょうか？

**Comment by rust** [comment]
確かに省略できた方がいいので、ちょっと検討してみます

**Comment by rust** [comment]
@r7kamura 

ちょっと調べてみたのですが、Railsのデフォルトではアクション定義が存在しないと `before_action` などが呼ばれないため、 `register_mobile` が呼ばれずに現状の挙動になるようです。

なのでやるのであれば、

- 設定を追加して有効 `true` && PC用(デフォルト)のビューがない場合 -> `register_mobile` 相当を実行して fallback する

かなと思うんですが、デフォルトの挙動を変更しすぎるし、あまり乗り気ではないというのが正直なところです。

**Comment by r7kamura** [comment]
> Railsのデフォルトではアクション定義が存在しないと before_action などが呼ばれない

なるほどー、知らなかった。

これはRails的には意図した挙動って感じなんですかねえ。ミスってそうなってる可能性もありそうですが。
そうであれば、ちょっとjpmobile側で対応するのは微妙そうですし、今回は諦めるほうが良いかも。

Railsが意図的にそうしているのかどうか、というのは自分のほうで少し調べてみます。

**Comment by r7kamura** [comment]
`rails new` した簡単なRails 7.0.3のアプリで試してみたんですが、app/views/home/index.html.erb の存在するアプリで

```ruby
class HomeController < ApplicationController
  before_action do
    raise
  end
end
```

を試してみると、`before_action` は実行されているように見えますね。

```
Started GET "/" for ::1 at 2022-06-06 11:20:46 +0900
   (0.3ms)  SELECT sqlite_version(*)
Processing by HomeController#index as HTML
Completed 500 Internal Server Error in 9ms (ActiveRecord: 0.0ms | Allocations: 1642)


  
RuntimeError ():
  
app/controllers/home_controller.rb:3:in `block in <class:HomeController>'
```

**Comment by r7kamura** [comment]
Railsのコードを読んでみると、メソッド定義は無いがテンプレートがある場合は代わりに `#default_render` メソッドを呼ぶぞ、という処理を `ActionController::ImplicitRender#method_for_action` が司っているようです。

https://github.com/rails/rails/blob/e494efde0808eb85a4cae6b3e87b7cf358517070/actionpack/lib/action_controller/metal/implicit_render.rb#L52-L56

`ActionController::Base#method_for_action` では、メソッド定義があるときだけそれを呼ぶという処理になっていて、これをOverrideしている、ということですね。このことは、`ActionController::Base#method_for_action` のコメントでも触れられている。

- https://github.com/rails/rails/blob/e494efde0808eb85a4cae6b3e87b7cf358517070/actionpack/lib/abstract_controller/base.rb#L261-L263

そうであれば、jpmobileでは、この `#method_for_action` で行われている「メソッド定義は無いがテンプレートがある場合は代わりに `#default_render` メソッドを呼ぶ」という処理をOverrideして対応するのが適切ではないかと考えています

**Comment by rust** [comment]
> rails new した簡単なRails 7.0.3のアプリで試してみたんですが、app/views/home/index.html.erb の存在するアプリで

「ビューが存在しない場合」が抜けてました 🙏

**Comment by r7kamura** [comment]
要するに、こういう感じのメソッドを提供してくれるmoduleを追加すると良いのでは？と思ってますがいかがでしょう？

```ruby
class HomeController < ApplicationController
  private

  # @note Override.
  def default_render
    if template_exists?(action_name.to_s, _prefixes, mobile: ['smart_phone'])
      render
    else
      super
    end
  end

  # @note Override.
  def method_for_action(action_name)
    super || if template_exists?(action_name.to_s, _prefixes, mobile: ['smart_phone'])
      'default_render'
    end
  end
end
```

p.s. `mobile: ['smart_phone']` のとこをどうやって書くのか分からなかったので上の例では雑にハードコートしてます

**Comment by rust** [comment]
こちらでもいろいろ調べて考えたんですが、 Jpmobile としては対応しないことにしました。

経緯としては、この処理ですが、

- `register_mobile` があるコントローラーかどうかを `Jpmobile::ViewSelector` が include されているかどうかを確認する

というのをやらないと多分意図通りにならず、なおかつ、

- 例えば `show_smart_phone.html.erb` しかないのが意図通りではない場合に問題なく動いてしまうことになる

ため、やるならオプション設定の追加(デフォルトで `false`)なんですが、この手のオプションを積極的に追加するのはやりたくないのと、そもそもこの機能が必要になるアクションがそんなに多くないと思っているというのが理由です。

**Comment by r7kamura** [comment]
なるほど。

コントローラーでメソッドを1個だけ上書きすれば良いだけだと考えたので、https://github.com/jpmobile/jpmobile/pull/202 を出してみたんですが、jpmobileの方針と違えていそうであれば、このIssueもろともCloseしてもらって全然OKです 👍
