### ISSUE TITLE
元々_mobileとついているテンプレートファイル名が使えない

### ISSUE THREAD

**Issue by nog** [jpmobile/jpmobile#206]
以下のようなControllerのAction
```ruby
  def example
    render "example/dummy_mobile"
  end
```
に対し`app/views/example/dummy_mobile.html.erb`を用意しているような時に問題が発生します。

ViewSelectorをinclludeした状態でこのようなrenderがRails6.1.6.1  jpmobile 6.1.2 ではは動いていましたが、Rails7.0.3.1 jpmobile7.0.3では動かなくなりました。
モバイル端末のUser-AgentでもそうでないUser-Agentでも`ActionView::MissingTemplate`が発生します。

Resolverの仕様変更によるものかと思います。
非モバイル端末向けにモバイルに関する説明をするページでこのような名前のテンプレートが使用されていて気付きました。

**Comment by nog** [comment]
6系と挙動が変わっていたのでissueはあげましたが、修正するかと実装追いかけたところ修正はかなり難しそうな印象を持ちました。
利用側の対応はテンプレートファイル名をjpmobileルールとバッティングしないように変更するだけで容易でかつ、そもそもバッティングすような命名をするなという話ではあるので仕様としてcloseしてもらっても全く問題ないです。

**Comment by rust** [comment]
これなんですが、Rails 7になったときにファイル名を解決する Resolver の挙動が変わってしまっていて、`action` 名を持っていけなくなったことが要因です。結構大掛かりな改変をすると対応はできると思うのですが、Rails 7以降は仕様として非対応にさせてください 🙏

**Comment by nog** [comment]
了解しました。closeしておきます！ありがとうございます！
