### ISSUE TITLE
ApplicationController::Liveがtest_case.rbで定義されたnew_controller_threadを呼ぶ

### ISSUE THREAD

**Issue by abnokubi** [jpmobile/jpmobile#248]
https://github.com/jpmobile/jpmobile/blob/31f93e98638ca988fcf092660ee934c2dc48b2fa/lib/jpmobile/hook_test_request.rb#L1

`require 'action_controller/test_case'` を実行しているため、ApplicationController::Liveが呼び出すnew_controller_thread が test_case.rb で定義されているメソッドに置き換えられてしまう。

その結果、event-sreamを ApplicationController::Live を使って実装すると、すべての出力がバッファリングされ、コネクションが切れるまでレスポンスが帰ってこなくなる。
https://api.rubyonrails.org/v7.0.4.2/classes/ActionController/Live.html

hook_test_request.rb の内容をコメントアウトすることで、event-streamが正常に動作する。
ただし、Rack::ETagに対するワークアラウンド(Last-Modifiedヘッダの付与)は必要。
https://github.com/rack/rack/issues/1619

実験環境
* Riby 3.0.4
* Rails 7.0.4.3
* Jpmobile 7.0.3

**Comment by rust** [comment]
@abnokubi こちらの現象の最小再現コードはどこかにあったりしますか？

**Comment by abnokubi** [comment]
@rust 
用意をしてみようと思いますのでちょっと待っていただけますか

**Comment by abnokubi** [comment]
@rust 
https://github.com/abnokubi/jpmobile-live-test
こちらに用意してみました。

jpmobileを入れると以下の出力がバッファリングされて、streamがcloseされるまで出力されません。
jpmobileを削除すると期待通りの動作をします。

```
curl -i http://localhost:4000/stream/index
HTTP/1.1 200 OK
Content-Type: text/event-stream
Last-Modified: 0
Cache-Control: no-cache
X-Request-Id: 250f02fc-8721-4276-8409-6884187a5591
X-Runtime: 2.002774
Server-Timing: start_processing.action_controller;dur=0.10, process_action.action_controller;dur=2001.02
Transfer-Encoding: chunked

data: {"name":"test"}

data: {"name":"test"}
```

**Comment by rust** [comment]
@abnokubi リポジトリが閲覧できないようです 🙏

**Comment by rust** [comment]
@abnokubi 手元で、

```ruby
class LiveSampleController < ApplicationController
  include ActionController::Live

  def stream
    response.headers['Content-Type'] = 'text/event-stream'
    response.headers['Last-Modified'] = Time.now.httpdate
    10.times {
      response.stream.write "hello world\n"
      sleep 1
    }
  ensure
    response.stream.close
  end
end
```

で再現したので #249 https://github.com/rust/jpmobile/tree/avoid-test-request で改善できたと思うのですが、確認してもらえますか。

**Comment by abnokubi** [comment]
@rust 
すみません、コードが見られない状態でした
改善したことを確認できました。ありがとうございます。
https://github.com/abnokubi/jpmobile-live-test/commit/8010375a00ed6ff2fcf4888a6cc54485501ce39c

**Comment by rust** [comment]
@abnokubi 7.0.4をリリースしました。これでも問題があるようならこのissueをReopenしてください 🙏
