### ISSUE TITLE
7.0.4 のタグとコミットが push されていなさそうです

### ISSUE THREAD

**Issue by tricknotes** [jpmobile/jpmobile#250]
7.0.3 と 7.0.4 の差分を確認したところ、 main ブランチとの差分が `lib/jpmobile/version.rb` のみだったため、バージョンアップのコミットが push されていないものと推測しました。

@rust 
もしお手元にコミットがあれば、push お願いできますでしょうか。

**Comment by rust** [comment]
@tricknotes 先ほど push してみました 🙏

**Comment by tricknotes** [comment]
さっそくありがとうございました！
確認できたので、クローズしますね
