### ISSUE TITLE
一部の端末でスマートフォンからのアクセスと判断されない件

### ISSUE THREAD

**Issue by suiyujin** [jpmobile/jpmobile#90]
Chrome Developer Toolsのモバイル向けデバッグ機能を利用して動作を確認したところ、下記の端末ではスマートフォンからのアクセスと判断されませんでした。
- BlackBerry Z30

![image](https://cloud.githubusercontent.com/assets/4738635/8390883/f1096e54-1ce4-11e5-9430-aa1210a967a2.png)
- Nokia N9

![image](https://cloud.githubusercontent.com/assets/4738635/8390884/ff9bc6e2-1ce4-11e5-8411-7c06aea4301d.png)
- Apple iPhone 6 (正しくスマートフォンと判断されている)

![image](https://cloud.githubusercontent.com/assets/4738635/8390879/dfffedd6-1ce4-11e5-867b-fb96cbf58fee.png)

これらの端末にはなぜ対応していないのでしょうか。
理由などあれば教えていただけると幸いです。

**Comment by rust** [comment]
報告有り難うございます。

BlackBerryなどのAndroid/iOS/WindowsPhone以外の端末については現在対応していません。

と言うのも、そもそもこれらの端末でスマホの画面を見せればいいのか、PCの画面を見せればいいのかを決められなかったため、ひとまずデフォルトであるPCのままにしておいているという状態です。

どちらのほうがいいと思われますか？

**Comment by suiyujin** [comment]
お返事ありがとうございます。
私も、Android/iOS/WindowsPhoneのみの対応で問題ないと思います。

端末の対応状況をドキュメントへ記述しておくと、利用者が対応状況を把握できるため良いかと考えたのですがいかがでしょうか。

**Comment by rust** [comment]
そうですね、可能なら修正のPRいただけると助かります :pray:
