### ISSUE TITLE
メール機能を使用するためにはActionMailerが必要であることが明記されていない

### ISSUE THREAD

**Issue by hoshitocat** [jpmobile/jpmobile#91]
### 問題点
- 依存関係のライブラリにActionMailerが無い
- ActionMailerがインストールされていない環境下では、メール機能が提供できない可能性がある
### 改善策
- Railsアプリ環境下でのみ動作を期待する場合
  WikiかREADMEに注意書きを追加する
- Railsアプリ環境下意外で動作を期待する場合

``` ruby
gem.add_runtime_dependency 'actionmailer' # jpmobile.gemspec
```

**Comment by rust** [comment]
おそらく[このあたり](https://github.com/jpmobile/jpmobile/blob/master/spec/unit/mail_spec.rb#L345-L347)のことを指していると思うのですが、これは`ActionMailer`ではなく`Mail` gemの機能です。
