### ISSUE TITLE
READMEにRailsアプリで使用する例を記述する

### ISSUE THREAD

**Issue by hoshitocat** [jpmobile/jpmobile#93]
#### 例
- Railsで利用する場合

Add this to your Gemfile:

``` ruby
gem 'jpmobile'
gem 'jpmobile-ipaddresses'
gem 'jpmobile-terminfo'
```

**Comment by rust** [comment]
どういうふうに書けばわかりやすくなるでしょうか。もしよかったらPR送っていただけると :pray:

**Comment by rust** [comment]
https://github.com/jpmobile/jpmobile/blob/main/CONTRIBUTING.md に記載したのでこちらは closes
