### ISSUE TITLE
ドキュメントの環境変数envへのリンク先が空白

### ISSUE THREAD

**Issue by pyonnuka** [jpmobile/jpmobile#97]
> 環境変数 env にキャリアクラスのインスタンスが格納されています。また Rack::Request#mobile としても取得可能です。

envのリンク（http://%27rack.jpmobile%27/）にアクセスしたところ、白ページになる。
おそらく携帯電話でアクセスしたときのみキャリアクラスが見えるので、その旨をドキュメントに記す。

環境　　：Mac OS X
ブラウザ：Chrome Version 43.0.2357.130

**Comment by rust** [comment]
see #101
