### ISSUE TITLE
rbenv環境でrake testを実行するのに必要なパッケージについて

### ISSUE THREAD

**Issue by hytkgami** [jpmobile/jpmobile#98]
**概要**

rbenv環境にてテストに必要なパッケージに足りないパッケージがあります。(ruby2.1)

**手順**

ドキュメントに書いてあるgemパッケージ
- sqlite3-ruby
- nokogiri
- rspec
- rspec-rails
- rspec-fixture
- rack-test
- mocha
- geokit

をインストールして

> rake test

を実行しても下記エラーが起きます。

> .rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rspec/its (LoadError)

**解決策**

> gem install rspec-its

rspec-itsパッケージをインストールすると`rake test`が動きます。
rbenvで管理するgemパッケージの中にrspec-itsが無いとダメなようです。

ドキュメントの[テストに必要なgemパッケージ](https://github.com/hytkgami/jpmobile#テストに必要なgemパッケージ)にrspec-itsを追加されると良いかと思います。
また、Gemfileに必要なパッケージがあらかじめ記述されていると導入の手間が省けると思うのですが、いかがでしょうか。

**Comment by rust** [comment]
こちらですが jpmobile のディレクトリで

```
$ bundle install
$ rake test
```

すればすべてインストールされると思うのですが、どうでしょうか。
