### ISSUE TITLE
request.mobile.displayがNilclassになってしまう

### ISSUE THREAD

**Issue by pyonnuka** [jpmobile/jpmobile#99]
jpmobile-terminfo をインストールした状態で次のコードをviewに書くと、
widthがNoMethodErrorになる。

```
画面幅 <%= request.mobile.display.width %>
```

環境：Mac OS X

期待する値：
request.mobile.displayでJpmobile::Display クラスのインスタンスが返ってくること。

実際の値：
request.mobile.displayがNilClass

原因：
jpmobile-terminfoはガラケーの画面サイズのみ取得することができること。

改善点：
jpmobile-terminfoはガラケーの画面サイズのみ取得することができ、
スマホとPCの画面サイズは取得できないという旨をドキュメントに記す。

**Comment by rust** [comment]
:+1:

**Comment by rust** [comment]
- ガラケー自体が既に終了している or しつつある
- 端末サイズを取得するようなニーズが今後発生しない可能性が非常に高い

ため、ドキュメントへの明記も含めて対応は取りやめます 🙏
